### ISSUE TITLE
'npm install' producing errors

### ISSUE THREAD

**Issue by AaronNGray** [okcoker/taggle.js#111]
`npm install` is producing errors on Windows, mainly with versions and 'sass' but this does not seem to effect `npm test` AFAICS on a quick run. I will try on Linux and Mac and report back.

**Comment by okcoker** [comment]
I develop on Mac but this doesn't really seem like an issue with the library itself.

Since the `grunt-sass` package uses `node-sass` maybe try `npm rebuild node-sass`?

**Comment by AaronNGray** [comment]
Yeah I remember now it is a Windows. It keep getting stuck behind on versioning on native packages (something to do with node-gyp and friends).

IIRC I bumped the node-sass version in the project and the problem went away.

FYI
```
C:\Users\aaron\Examples\taggle.js>npm i

> node-sass@3.13.1 install C:\Users\aaron\Examples\taggle.js\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-59_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\Users\aaron\Examples\taggle.js\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\aaron\Examples\taggle.js\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\aaron\\Examples\\taggle.js\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (C:\Users\aaron\Examples\taggle.js\node_modules\which\which.js:40:28)
gyp verb `which` failed     at E (C:\Users\aaron\Examples\taggle.js\node_modules\which\which.js:43:29)
gyp verb `which` failed     at C:\Users\aaron\Examples\taggle.js\node_modules\which\which.js:54:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at F (C:\Users\aaron\Examples\taggle.js\node_modules\which\which.js:40:28)
gyp verb `which` failed     at E (C:\Users\aaron\Examples\taggle.js\node_modules\which\which.js:43:29)
gyp verb `which` failed     at C:\Users\aaron\Examples\taggle.js\node_modules\which\which.js:54:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at F (C:\\Users\\aaron\\Examples\\taggle.js\\node_modules\\which\\which.js:40:28)\n    at E (C:\\Users\\aaron\\Examples\\taggle.js\\node_modules\\which\\which.js:43:29)\n    at C:\\Users\\aaron\\Examples\\taggle.js\\node_modules\\which\\which.js:54:16\n    at FSReqWrap.oncomplete (fs.js:166:21)' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at F (C:\Users\aaron\Examples\taggle.js\node_modules\which\which.js:40:28)
gyp verb `which` failed     at E (C:\Users\aaron\Examples\taggle.js\node_modules\which\which.js:43:29)
gyp verb `which` failed     at C:\Users\aaron\Examples\taggle.js\node_modules\which\which.js:54:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at F (C:\Users\aaron\Examples\taggle.js\node_modules\which\which.js:40:28)
gyp verb `which` failed     at E (C:\Users\aaron\Examples\taggle.js\node_modules\which\which.js:43:29)
gyp verb `which` failed     at C:\Users\aaron\Examples\taggle.js\node_modules\which\which.js:54:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at F (C:\\Users\\aaron\\Examples\\taggle.js\\node_modules\\which\\which.js:40:28)\n    at E (C:\\Users\\aaron\\Examples\\taggle.js\\node_modules\\which\\which.js:43:29)\n    at C:\\Users\\aaron\\Examples\\taggle.js\\node_modules\\which\\which.js:54:16\n    at FSReqWrap.oncomplete (fs.js:166:21)' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\aaron\Examples\taggle.js\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\aaron\Examples\taggle.js\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\aaron\Examples\taggle.js\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aaron\\Examples\\taggle.js\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\aaron\Examples\taggle.js\node_modules\node-sass
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN karma-sinon-chai@1.3.3 requires a peer of sinon@^2.1.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aaron\AppData\Roaming\npm-cache\_logs\2018-03-09T13_17_35_131Z-debug.log
```
